### ISSUE TITLE
Device Detection

### ISSUE THREAD

**Issue by dehnhardt** [dehnhardt/mioconfig#14]
@trebmuh I can not open the last Issue anymore, so I create a new one. 
one abbreviation wasn't enough, so I abbreviated "Nom du périph." (hopefully that's true) and then made the window a little wider. I suppose, if the French names fit, most other languages would fit as well ;-)
Here is another screenshot.
![devicedetection2](https://user-images.githubusercontent.com/5556832/52882159-1aa62780-3167-11e9-96dc-64384faf4e65.png)

**Comment by dehnhardt** [comment]
If you can close the other issue please do so!

**Comment by trebmuh** [comment]
Hi @dehnhardt yes, ok, it looks fine like that.

For the #8 issue, I can't access it anymore too. I've sent a request to github, we'll see what they do answer.

Cheers.

**Comment by trebmuh** [comment]
FWIW, I've been updating Firefox (Debian stable "Stretch") here, and I had access back to the #8 issue. I closed it now.
