### ISSUE TITLE
iConnConfig and LibraZiK-2

### ISSUE THREAD

**Issue by trebmuh** [dehnhardt/mioconfig#17]
Hi @dehnhardt ,
usually, I'm sending an email to the upstream developer for that but I can't find one for you. Hence this "issue".

Just to let you know that, as of today, iConnConfig 0.1~gitbd46c3c has it the LibraZiK-2's users repo.

Thanks for this software!

PS: feel free to close this "issue" when you have read it.

**Comment by dehnhardt** [comment]
Hmm how can get an upstream developer?

**Comment by trebmuh** [comment]
DISCLAIMER: I'm not sure that I understood your message.

For my point of view: you're the _usptream developer_ and I'm _downstream_. Usually there is a contact email for the upstream developer (_you_) in the sources files, and in a AUTHOR text file on the root directory.

**Comment by dehnhardt** [comment]
@trebmuh Thanks for your explanation. I will add an AUTHOR file to the repository. That exactly was my question;-)

**Comment by trebmuh** [comment]
Nice, thanks for the new AUTHOR.md file.
I'm closing this issue then.
