### ISSUE TITLE
Build dependencies

### ISSUE THREAD

**Issue by taisto** [dehnhardt/mioconfig#2]
After following the build instructions I get an error during compilation with qt4.8:
`In file included from src/main.cpp:1:0:
src/miomain.h:8:30: fatal error: QCommandLineParser: Datei oder Verzeichnis nicht gefunden
 #include <QCommandLineParser>
`
From searching online I get the impression, that QCommandLineParser was introduced with qt5.2.

**Comment by dehnhardt** [comment]
Ok, again I broke the compatibility with QT4.8...
Qt5.2 is about 3 Years old. Do you think backward compatibility to QT4.x ist still needed? What distro are you on?

**Comment by taisto** [comment]
After retrying with QT5 compilation works fine for me. I guess all it takes is an update of the build instructions.

**Comment by dehnhardt** [comment]
updated the buid depencencies

**Comment by MatthewGitter** [comment]
$ make
g++ -c -m64 -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -DQT_DEPRECATED_WARNINGS -D__LINUX_ALSA__ -D__MIO_DEBUG__ -D__RTMIDI_DEBUG__ -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/libusb-1.0 -I. -I. -o main.o src/main.cpp
In file included from src/main.cpp:1:0:
src/iconnconfigmain.h:8:10: fatal error: QCommandLineParser: No such file or directory
 #include &lt;QCommandLineParser&gt;
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:516: recipe for target 'main.o' failed
make: *** [main.o] Error 1
$ locate QCommandLineParser
/usr/include/x86_64-linux-gnu/qt5/QtCore/QCommandLineParser

**Comment by dehnhardt** [comment]
@MatthewGitter Do you use QT >= 5.2?

**Comment by MatthewGitter** [comment]
After I ran
------------------------------
$ sudo apt-get install qt4-qmake-dev libqt4-dev libasound2-dev libusb-
1.0-0-dev 
------------------------------

to satisfy other installation dependencies, but still failed on
QCommandLineParser:
------------------------------ 
$ qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
$ pkg-config --modversion QtCore
4.8.7
------------------------------

**Comment by dehnhardt** [comment]
Then everything is ok. You still need QT5.2 or later and as you clearly stated you have only4.8.x.

**Comment by MatthewGitter** [comment]
It was already installed (as per https://github.com/dehnhardt/iconnconfig/blob/master/BUILD.md ): 
------------------------------------------
$ sudo apt-get install qtbase5-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
qtbase5-dev is already the newest version (5.9.5+dfsg-0ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
------------------------------------------

**Comment by MatthewGitter** [comment]
I noticed in the BUILD.md doc that I needed to install libclalsadrv-dev , so I did. I ran `qmake -qt=5 ; make` again (this time including the `-qt=5`). This time no problem (except a warning on a switch/case default fallthru) building, and it runs and finds my device. I suppose it what the `-qt-5` switch to qmake that made the difference.

**Comment by dehnhardt** [comment]
Ok, thanks for the finding. I will add that tip that in the dependencies file,
