### ISSUE TITLE
Crashing Damage

### ISSUE THREAD

**Issue by MatthewGitter** [dehnhardt/mioconfig#4]
I noticed in the [release notes](https://github.com/dehnhardt/iconnconfig/blob/master/RELEASENOTES.md) problems with reading settings from (device) flash or restoring (device) to factory default the application might crash:

> known problems
> 
> in general error handling is currently nearly not implemented. I still don't have a concept
> (1) after reading the settings from flash or restoring to factory default, the application might crash - I'm still not sure what the problem is.
> 

Is there any risk of corrupting the device or otherwise leaving it in an unstable state?

FWIW the notes say:

> v.01.
> Linux
> Tested only with MIO10

Maybe they need to be updated? I believe it's tested OK with iConnectMIDI4+ etc.

**Comment by dehnhardt** [comment]
I have had no problems with the devices - but I can't guarantee it. It's the application which crash when trying to reflect the changes in the device (as far as I remember).
I used this functinality only a few times until my device was set up properly. That's also the reason why I stopped debugging it further :-(
