### ISSUE TITLE
GUI questions

### ISSUE THREAD

**Issue by trebmuh** [dehnhardt/mioconfig#8]
Hi @dehnhardt 
Here are a few screenshots I took from the software:
![iconnconfig-1](https://user-images.githubusercontent.com/8705846/52716914-1da2eb80-2fa0-11e9-9eba-0178a8add8dc.png)
![iconnconfig-2](https://user-images.githubusercontent.com/8705846/52716926-24316300-2fa0-11e9-915a-00284717455a.png)
![iconnconfig-3](https://user-images.githubusercontent.com/8705846/52716931-2c899e00-2fa0-11e9-910e-7572a80490b1.png)

I'm wondering 2 things:
1. on the 2nd screenshot, we can see that some parts are not translated (and they doesn't look to be a part of the .ts file)
2. there is no picture/image/icon and I'm wondering if this is expected or if something is wrong.

_please, note that I don't have any icon devices at hand, and I'm mainly trying to get this software packaged to include it in my linux-audio distribution called LibraZiK_

**Comment by dehnhardt** [comment]
Dear Olivier,
1. I'll take a look at it and correct it. But I don't expect it to be until the weekend. 
2. The currently is no Icon - and I'm abolutely not good at making icons and graphics... -( 
If you include the program in your distrubution, which really pleases me, then I would like to add "Attention, this is software in alpha stage" at some place. So far only a few have tested it...

Be sure, I will look into your distribution very soon. I'm always intereted in such things;-)
All the best
Holger

**Comment by dehnhardt** [comment]
1. Should already be fixed with changes from JP Cimalando.

**Comment by trebmuh** [comment]
No worries at all Holger, it's now packaged in the "testing" repo, and I'll make sure to put a disclaimer about the alpha-stage.

**Comment by trebmuh** [comment]
Nice for 1 @jpcima thank you!

Following request is that now we've got that:
![iconnconfig](https://user-images.githubusercontent.com/8705846/52797156-94f67f00-3075-11e9-9585-3aa304bc753b.png)

Could we make it so the width of each column automatically fit with the size of the writings?

**Comment by dehnhardt** [comment]
I will do my best;-)

**Comment by trebmuh** [comment]
Thanks :)

**Comment by dehnhardt** [comment]
This should be ok now.

**Comment by trebmuh** [comment]
Thank you @dehnhardt it's much more OK than before!

If I can ask, could you please make the windows to auto-adapt to the content? Right now, one have to scroll right to get the end of the 3rd column. If it could be avoided, it'd be great! If not, that's not of a big deal, we can live with that!

![iconnconfig1](https://user-images.githubusercontent.com/8705846/52872181-23d5cb00-314c-11e9-8053-3e178a441355.png)

![iconnconfig2](https://user-images.githubusercontent.com/8705846/52872184-27695200-314c-11e9-85c0-054d74781d3d.png)

**Comment by dehnhardt** [comment]
Olivier, the information in the columns of the table after the devices have been detected is quite narrow. (See picture) So I don't know if it makes sense to enlarge the window that way.
Would it be possible to abbreviate the French designations? (Unfortunately I don't speak a word french, so I can't decide if it's ok...)
![devicedetection](https://user-images.githubusercontent.com/5556832/52875639-1ffa7680-3155-11e9-8039-3502d2bf8fed.png)

**Comment by trebmuh** [comment]
Yes, probably a good solution. Done in #13 .
